version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: demo
  app:
    build: .
    ports:
      - "3040:80"
    volumes:
      - ./app:/var/www/html